development: &common
  adapter: postgresql
  encoding: unicode
  database: child_health_system_dev
  pool: 5
  username: rails
  password: password
  host: localhost


production:
  <<: *common
  user: rails
  database: child_health_system_production
  password: 
  host: 