# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a45692c660e64280265a9a1f9c39944a00ed2e31c3d6810bf7b9e12a459c3b68ed8c1d3dd48f889ee225454aa7895cee7b35008eafea66d84f47a24bd66b4a6f

test:
  secret_key_base: 5fc9c3538d3a772ff5c3b3e1c17611b5b6815320474fddb1281d2104ad79aaf86f122fdca745a41f83038ec7cbe56792c4766d7079b44a8a065bdc3e53b8977e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
